"""
ComfyUI-JM-Gemini-API Nodes

This package contains all Gemini API related nodes.
"""

from .jm_gemini_image_node import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS
from .jm_gemini_image_node import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS

from .jm_gemini_video_node import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS
from .jm_gemini_video_node import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS

from .jm_gemini_watermark_remover import NODE_CLASS_MAPPINGS as WATERMARK_NODE_CLASS_MAPPINGS
from .jm_gemini_watermark_remover import NODE_DISPLAY_NAME_MAPPINGS as WATERMARK_NODE_DISPLAY_NAME_MAPPINGS

from .jm_gemini_reverse_node import NODE_CLASS_MAPPINGS as REVERSE_NODE_CLASS_MAPPINGS
from .jm_gemini_reverse_node import NODE_DISPLAY_NAME_MAPPINGS as REVERSE_NODE_DISPLAY_NAME_MAPPINGS

from .gemini_word import NODE_CLASS_MAPPINGS as WORD_NODE_CLASS_MAPPINGS
from .gemini_word import NODE_DISPLAY_NAME_MAPPINGS as WORD_NODE_DISPLAY_NAME_MAPPINGS
from .gemini_position import NODE_CLASS_MAPPINGS as POSITION_NODE_CLASS_MAPPINGS
from .gemini_position import NODE_DISPLAY_NAME_MAPPINGS as POSITION_NODE_DISPLAY_NAME_MAPPINGS
from .gemini_pic import NODE_CLASS_MAPPINGS as PIC_NODE_CLASS_MAPPINGS
from .gemini_pic import NODE_DISPLAY_NAME_MAPPINGS as PIC_NODE_DISPLAY_NAME_MAPPINGS

try:
    from .gemini_xls import NODE_CLASS_MAPPINGS as XLS_NODE_CLASS_MAPPINGS
    from .gemini_xls import NODE_DISPLAY_NAME_MAPPINGS as XLS_NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    XLS_NODE_CLASS_MAPPINGS = {}
    XLS_NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS = {
    **IMAGE_NODE_CLASS_MAPPINGS,
    **VIDEO_NODE_CLASS_MAPPINGS,
    **WATERMARK_NODE_CLASS_MAPPINGS,
    **REVERSE_NODE_CLASS_MAPPINGS,
    **WORD_NODE_CLASS_MAPPINGS,
    **POSITION_NODE_CLASS_MAPPINGS,
    **PIC_NODE_CLASS_MAPPINGS,
    **XLS_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
    **WATERMARK_NODE_DISPLAY_NAME_MAPPINGS,
    **REVERSE_NODE_DISPLAY_NAME_MAPPINGS,
    **WORD_NODE_DISPLAY_NAME_MAPPINGS,
    **POSITION_NODE_DISPLAY_NAME_MAPPINGS,
    **PIC_NODE_DISPLAY_NAME_MAPPINGS,
    **XLS_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
